fix(data.yml): fix push and pull

diff --git a/.github/workflows/data.yml b/.github/workflows/data.yml
--- a/.github/workflows/data.yml
+++ b/.github/workflows/data.yml
@@ -62,11 +62,17 @@ jobs:
 
       - name: Commit and push analysis result
         run: |
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
-          git -c submodule.recurse=false pull --rebase origin main || true
-          
-          git add results/*.pdf
-          git commit -m "docs: add bag analysis report from ${{ inputs.bag_file_name }}"
-          
-          git push origin main
+            git config user.name "github-actions"
+            git config user.email "github-actions@github.com"
+            git -c submodule.recurse=false pull --rebase origin main || true
+
+            git add results/*.pdf
+            git commit -m "docs: add bag analysis report from ${{ inputs.bag_file_name }}"
+
+            git push origin main || (
+              echo "First push failed, pulling latest changes and retrying..." &&
+              git -c submodule.recurse=false pull --rebase origin main &&
+              git rebase &&
+              sleep 3 &&
+              git push origin main
+            )
